### ISSUE TITLE
Bevalling en Baring: Observation, Procedure of Encounter

### ISSUE THREAD

**Issue by mgraauw** [mgraauw/geboortezorg-fhir#1]

**Comment by mgraauw** [comment]
Of Observation, en dan in Snomed findings gebruiken

**Comment by LilianMinne** [comment]
Ik heb het even laten bezinken en het is misschien nog niet eens zo'n gek idee. Een bevalling is een gebeurtenis en volgens de spec is Observation een event resource. Als je vervolgens verder leest dan blijkt dat Procedure een "specialisatie" is van Observation:

_There are other resources that can be considered "specializations" of the Observation resource and should be used for those specific contexts and use cases. They include AllergyIntolerance resource, FamilyMemberHistory resource, Procedure resource, and Questionnaire resource._ 

In het geval van een bevalling lijkt de specialisatie Procedure te specifiek, omdat de bevalling niet per definitie in het ziekenhuis plaatsvindt. De ziekenhuisbevalling kan indien nodig alsnog gemapt worden op een Procedure, waarbij via het partOf element een link gelegd kan worden naar de Bevalling Observation.

De eerdere gedachte voor Encounter kwam ook voort uit het idee dat de bevalling zelf niet per definitie een Procedure is, maar er in principe wel kan worden uitgegaan van een contactmoment met de gynaecoloog/verloskundige (waarbij class kan worden gebruikt om aan te geven of dit in het ziekenhuis, thuis of virtueel <bijv. telefonische begeleiding> is). Echter is de bevalling zelf geen Encounter. Wel kan Encounter in aanvulling op Observation gebruikt worden om de aanwezigheid van verloskundige etc. in op te nemen.

Mogelijk dus alledrie de resources nodig:

- Observation - de bevalling
- Procedure - de ziekenhuisbevalling gekoppeld aan de Observation
- Encounter - het ziekenhuisbezoek of de aanwezigheid zorgverleners bij thuisbevalling

**Comment by mgraauw** [comment]
Voorlopige keuze:
Observation voor de bevalling
Encounter voor gegevens als partusassistentie e.d.
Procedure niet zeker of dit nodig is voor ziekenhuisbevalling. Keizersnede e.d. zijn uiteraard wel Procedure op zich.

**Comment by LilianMinne** [comment]
baring als part of van bevalling?

**Comment by LilianMinne** [comment]
besluit nav overleg woe 18/12 met anneke en arianne: 
- Procedure voor begeleiding van bevalling (DeliveryProcedure)
- Encounter voor partusassistentie (ChildBirthAssistance)
- Observation per fase van de bevalling (ontsluiting, uitdrijving en nageboorte) gekoppeld via partOf aan de DeliveryProcedure. Ontsluiting & nageboorte hebben max cardinaliteit 1, uitdrijving is per kind en heeft max cardinaliteit *

Daarna per mail besproken om ook nog extra Observation Birth toe te voegen om kindspecifieke uitkomstgegevens zoals geboortegewicht aan te koppelen.
